use yew::prelude::*;

pub enum Message<T: std::fmt::Display> {
    Warning(T),
    Tip(T),
    Stat(T),
    Info(T),
    Other(T),
    Danger(T),
}

impl<T: std::fmt::Display> Message<T> {
    pub fn as_html(&self) -> Html {
        match self {
            Message::Warning(message) => html! {
                <div><div class="warn_message"><b>{"Warning: "}</b>{message}</div><br/></div>
            },
            Message::Tip(message) => html! {
                <div><div class="tip_message"><b>{"Tip: "}</b>{message}</div><br/></div>
            },
            Message::Stat(message) => html! {
                <div><div class="stat_message">{message}</div><br/></div>
            },
            Message::Info(message) => html! {
                <div><div class="info_message"><b>{"Did you know? "}</b>{message}</div><br/></div>
            },
            Message::Other(message) => html! {
                <div><div class="unknown_message">{message}</div><br/></div>
            },
            Message::Danger(message) => html! {
                <div><div class="danger_message"><b>{"WARNING: "}</b>{message}</div><br/></div>
            },
        }
    }
}

pub const MESSAGES: [Message<&'static str>; 21] = [
    Message::Info("Only 35 persons are using this extension weekly."),
    Message::Info("Googleam has more than 1000 giveaways in its database."),
    Message::Info("The first version of the bot was a program controlling the browser throught a webdriver interface."),
    Message::Info("The music used in my youtube video introducing the version 2.0 was generated by an artifical intelligence."),
    Message::Info("This bot is entirely open-source. Check the code at https://github.com/Mubelotix/gleam.io-bot-extension."),
    Message::Info("This extension runs throught WASM, a brand new technology intended to run compiled programs in web browsers at native speed (almost)."),
    Message::Info("You are using the very last tool automating gleam.io entering."),
    Message::Info("This extension is written in Rust, the best programming language in the world."),
    Message::Tip("If you are experiencing issues, you can report them at mubelotix@gmail.com."),
    Message::Tip("Feel free to send me your ideas in order to improve the extension. (mubelotix@gmail.com)"),
    Message::Tip("I recommend using special social media accounts on gleam.io to avoid tainting your personnal account."),
    Message::Tip("Strategically, it's rarely a good idea to share a giveaway."),
    Message::Tip("Don't lose your time on random giveaways that don't even interest you."),
    Message::Tip("Smaller giveaways are more profitable because larger giveaways are almost impossible to win."),
    Message::Tip("Use Googleam instead of its competitors to benefit from a powerful search engine."),
    Message::Warning("Your email address could be used to subscribe to newsletters in exchange for entries."),
    Message::Warning("Avoid launching multiple bot processes simultaneously. It would disturb third parties servers."),
    Message::Warning("A significant part of giveaways is scams. I would say around 10%."),
    Message::Warning("Gleam.io is using trackers. Consider taking measures to protect your privacy."),
    Message::Warning("You could be notified of a win by another medium than mails because a lot of publishers are violating gleam.io's terms of use."),
    Message::Warning("Don't try multiple accounts on a single IP."),
];